# Generated by Django 5.0.4 on 2024-05-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_hotel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.CharField(max_length=50),
        ),
    ]
