# Generated by Django 5.0.4 on 2024-05-16 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_hotel_price_alter_hotel_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mahasiswa',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
