# Generated by Django 5.0.4 on 2024-05-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_mahasiswa_delete_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='reviews',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
