# Generated by Django 5.0.4 on 2024-05-16 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_hotel_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='reviews',
            new_name='review',
        ),
    ]
